### ISSUE TITLE
Make screens responsive for mobile devices

### ISSUE THREAD

**Issue by pranabs1ngh** [pranabs1ngh/quivia-webapp#3]
**Type of issue**: Enhancement
**Description**: By default, all screens are designed for 1920 X 1080p screens. All measurements are given in pixels.

**Todo**:
- [ ] Convert all measurements to responsive units.
- [ ] Add media query for mobile devices.

**Comment by RafaelCLopes** [comment]
Hello can I work on this issue?

**Comment by kellsbells** [comment]
Hey! I would love to work on this!
